import 'package:flutter/material.dart';

const Color kcBackgroundColor = Color(0xff121212);
const Color kcTransparentColor = Colors.transparent;
const Color kcPokedexColorGradientOne = Color(0xffdf4841);
const Color kcPokedexColorGradientTwo = Color(0xff902d27);
const Color kcUnselectedColor = Color(0xffB6B6B6);
const Color kcHintColor = Color(0xff4E4E4E);
const Color kcLightGrayColor = Color(0xff9e9e9e);
const Color kcGrayColor = Color(0xff2c2b2b);
const Color kcWhiteColor = Color(0xffffffff);
const Color kcProgressBarBackgroundColor = Color(0xff444949);

const Color kcTypeBugColor = Color(0xff9ebf4a);
const Color kcTypeDarkColor = Color(0xff5e5b6c);
const Color kcTypeDragonColor = Color(0xff3074b9);
const Color kcTypeElectricColor = Color(0xfff2d869);
const Color kcTypeFairyColor = Color(0xffe099df);
const Color kcTypeFightingColor = Color(0xffe099df);
const Color kcTypeFireColor = Color(0xfff2a461);
const Color kcTypeFlyingColor = Color(0xff97acdc);
const Color kcTypeGhostColor = Color(0xff5f6db3);
const Color kcTypeGrassColor = Color(0xff76c184);
const Color kcTypeGroundColor = Color(0xffcc8258);
const Color kcTypeIceColor = Color(0xff8dcfc4);
const Color kcTypeNormalColor = Color(0xffa0a2a0);
const Color kcTypePoisonColor = Color(0xffa56bc5);
const Color kcTypePsychicColor = Color(0xffeb8b87);
const Color kcTypeRockColor = Color(0xffd2c996);
const Color kcTypeSteelColor = Color(0xff6aa6aa);
const Color kcTypeWaterColor = Color(0xff6196d2);
